<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260227121557 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE us_action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, class_name VARCHAR(255) DEFAULT NULL, id_tag VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, module_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D71B028AFC2B591 ON us_action (module_id)');
        $this->addSql('CREATE TABLE us_module (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, route VARCHAR(255) DEFAULT NULL, position INT DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, class_name VARCHAR(255) DEFAULT NULL, id_tag VARCHAR(255) DEFAULT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_16991A92727ACA70 ON us_module (parent_id)');
        $this->addSql('CREATE TABLE us_user_action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, action_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BFBF579BA76ED395 ON us_user_action (user_id)');
        $this->addSql('CREATE INDEX IDX_BFBF579B9D32F035 ON us_user_action (action_id)');
        $this->addSql('ALTER TABLE us_action ADD CONSTRAINT FK_5D71B028AFC2B591 FOREIGN KEY (module_id) REFERENCES us_module (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE us_module ADD CONSTRAINT FK_16991A92727ACA70 FOREIGN KEY (parent_id) REFERENCES us_module (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE us_user_action ADD CONSTRAINT FK_BFBF579BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE us_user_action ADD CONSTRAINT FK_BFBF579B9D32F035 FOREIGN KEY (action_id) REFERENCES us_action (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE us_action DROP CONSTRAINT FK_5D71B028AFC2B591');
        $this->addSql('ALTER TABLE us_module DROP CONSTRAINT FK_16991A92727ACA70');
        $this->addSql('ALTER TABLE us_user_action DROP CONSTRAINT FK_BFBF579BA76ED395');
        $this->addSql('ALTER TABLE us_user_action DROP CONSTRAINT FK_BFBF579B9D32F035');
        $this->addSql('DROP TABLE us_action');
        $this->addSql('DROP TABLE us_module');
        $this->addSql('DROP TABLE us_user_action');
    }
}
